name: Ruff
on: [push]

jobs:
  ruff_py3:
    name: Ruff syntax check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          pip install --user ruff
      - name: ruff
        run: |
          ruff --format=github .
